version: '3.2'

services:

  nginx-proxy:
    restart: unless-stopped
    image: nginxproxy/nginx-proxy:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/app/nginx.tmpl
    networks:
      - null_signal


  acme-companion:
    restart: unless-stopped
    image: nginxproxy/acme-companion:latest
    container_name: nginx-proxy-acme
    environment:
      - DEFAULT_EMAIL=mail@yourdomain.tld
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - null_signal


  netrunner_cards_json:
    restart: none
    image: registry.digitalocean.com/nsgcr/netrunner-cards-json:latest
    volumes:
      - netrunner-cards-json:/mnt/netrunner-cards-json


  nrdb_api_server:
    restart: unless-stopped
    image: registry.digitalocean.com/nsgcr/nrdb-api-server:latest
    networks:
      - backend
      - null_signal
    env_file: .env
    # rely on the RAILS_ENV value of the host machine
    environment:
      - POSTGRES_PASSWORD
      - RAILS_ENV
    # starts the app container after the DB and netrunner_cards_json containers
    depends_on:
      - db-nrdb-api
      - netrunner_cards_json
    volumes:
      - ./config/database.yml:/var/www/nrdb-api/config/database.yml
      - netrunner-cards-json:/netrunner-cards-json
      - nrdb-api-logs:/var/www/nrdb-api/log


  cobra:
    restart: unless-stopped
    image: registry.digitalocean.com/nsgcr/cobra:latest
    networks:
      - backend
      - null_signal
    depends_on: 
      - db-cobra
    env_file: .env
    environment:
      - POSTGRES_PASSWORD
      - RAILS_ENV
    volumes:
      - ./config/database.yml:/var/www/cobra/config/database.yml
      - ./config/secrets.yml:/var/www/cobra/config/secrets.yml
      - cobra-logs:/var/www/cobra/log
      - cobra-assets:/var/www/cobra/public/assets
      - cobra-tmp:/var/www/cobra/tmp


  db-nrdb-api:
    restart: unless-stopped
    image: postgres:14.5-alpine
    networks:
     - backend
    env_file: .env
    environment:
      - POSTGRES_PASSWORD
    volumes:
      - nrdb-api-postgres:/var/lib/postgresql/data


  db-cobra:
    restart: unless-stopped
    image: postgres:14.5-alpine
    networks:
     - backend
    env_file: .env
    environment:
      - POSTGRES_PASSWORD
    volumes:
      - cobra-postgres:/var/lib/postgresql/data


  rules:
    restart: unless-stopped
    image: registry.digitalocean.com/nsgcr/netrunner-comprehensive-rules:latest

    volumes:
      - rules:/var/www/html
  

  rules-web:
    restart: unless-stopped
    image: php:8.2-cli-alpine

    ports:
      - "8999:80"

    depends_on: 
      - rules

    volumes:
      - rules:/var/www/html

    command:
      - php
      - -S
      - 0.0.0.0:80

    working_dir: /var/www/html


networks:
  backend:
  null_signal:


volumes:
  conf:
  vhost:
  html:
  certs:
  acme:
  nrdb-api-logs:
  nrdb-api-postgres:
  cobra-assets:
  cobra-logs:
  cobra-postgres:
  cobra-tmp:
  netrunner-cards-json:
  rules:
